### ISSUE TITLE
add way to expend the param to the description

### ISSUE THREAD

**Issue by regevbr** [mikejsdev/mocha-param#2]
will make it easier to understand what param caused the test to fail

**Comment by Kartkk** [comment]
It would be great if we have this feature implemented ASAP.

**Comment by achepukov** [comment]
+1

**Comment by enavarrocu** [comment]
In the meanwhile you can do something like this: 

```
const values = [
    {param: 1, result: false},
    {param: 2, result: false},
    {param: 3, result: true},
    {param: 4, result: true},
];

itParam('My test are: ', values, (value) => {
    console.log(value);
    expect(value.param > 2).to.equal(value.result);
});
```

When it fails will tell you which parameters make the test fail.

**Comment by aconrad** [comment]
I submitted a pull request to address this problem, please see https://github.com/mikejsdev/mocha-param/pull/4.

**Comment by mikejsdev** [comment]
This has beed added in version 2.0.0 which has now been published to npm!
