### ISSUE TITLE
Add the feature to parameterize the results for each parameterized test

### ISSUE THREAD

**Issue by jcmadrigalg** [mikejsdev/mocha-param#3]
Hi,
It would be great that could be a way to specify the expected results for each parameterized test.
Great project, thanks!

**Comment by enavarrocu** [comment]
@jcmadrigalg 

Something like this will do the trick:

```
const values = [
    {param: 1, result: false},
    {param: 2, result: false},
    {param: 3, result: true},
    {param: 4, result: true},
];

itParam('My test are: ', values, (value) => {
    expect(value.param > 2).to.equal(value.result);
});
```

You can do this as complex as you want.

**Comment by jcmadrigalg** [comment]
Hi @enavarrocu ,
That's great! 
Thanks for the trick, it worked as you say on the sample.
I'm learning Javascript and I have a lot to learn.

**Comment by enavarrocu** [comment]
No problem. Happy to help. You are on a good path already if you are checking this kind of stuff in your learning process.

**Comment by mikejsdev** [comment]
This has beed added in version 2.0.0 which has now been published to npm!
