### ISSUE TITLE
itParam does not take the modified value of the the data array parameter.

### ISSUE THREAD

**Issue by akshayamaldhure** [mikejsdev/mocha-param#7]
My Mocha spec is defined in a way that the `describe` has a global array (declared empty), which gets accessed and modified inside my first `it`. The second test is an `itParam` test which tries to access it, but finds it to be empty, as a result of which the `itParam` test does not run at all.

Example (`it` can access the modified global value):
```
describe('some test', function () {
    var value = 0;
    it('should pass a value', function (done) {
        value = 5;
        done();
    });
    it('and then double it', function (done) {
        console.log(value * 2); // 10
        done();
    });
});

```
Example (`itParam` cannot access the modified global value):
```
let itParam = require('mocha-param');

describe('some test', function () {
    var value = 0;
    it('should pass a value', function (done) {
        value = 5;
        done();
    });
    itParam('and then double it', [value], function (done, v) {
        console.log(v * 2); // 0
        done();
    });
});
```

**Comment by mikejsdev** [comment]
Interesting issue. I'd love to take a look at this issue but sadly I don't have the time at the moment. I'm more than happy to look at and review any pull requests from the community though if anyone can take a look?

**Comment by mikejsdev** [comment]
Happy to reopen if anyone else wants to look at this further.
