### ISSUE TITLE
Publishing last master to npm

### ISSUE THREAD

**Issue by NBaruK** [mikejsdev/mocha-param#9]
Hi, 
could you publish current version of master to npm? We are missing the last commit containing type definitions. 

Thank you.

**Comment by HoldYourWaffle** [comment]
Is there a reason why this hasn't been done yet?
It makes typescript usage a massive hassle.

**Comment by mikejsdev** [comment]
What exactly is it that you want published? Can someone make a pull request with type definitions in?

**Comment by HoldYourWaffle** [comment]
They are already included with #8, but this was never published.

**Comment by HoldYourWaffle** [comment]
Actually, those definition don't seem to be correct. I'll create PR with (in my opinion) improved ones.

**Comment by mikejsdev** [comment]
Thanks for the pull request. This has now been merged and published.

Please let me know if you have any problems.

**Comment by HoldYourWaffle** [comment]
Looks great, thank you so much for the quick response!
